---
title: The Hoary Gamer
repository: jkerley/hoarygamer_net
collections:
  music:
    title: Music
    output: true
    Author:
    - name
    - bio
    - image
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true

