---
title: The Hoary Gamer
repository: jkerley/hoarygamer_net
url: "https://www.hoarygamer.com/"
collections:
  music:
    title: Music
    output: true
    Author:
    - name
    - bio
    - image
  posts:
    title: Posts
    output: true
    permalink: none
  uploads:
    title: Uploads
    output: true


