---
title: The Hoary Gamer
timezone: UTC
collections:
  music:
    title: Music
    output: true
    Author:
    - name
    - bio
    - image
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: default
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
permalink: pretty
